# Generated by Django 4.0.3 on 2022-03-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'read'), ('write', 'write')], max_length=30)),
                ('role', models.CharField(choices=[('AUTHOR', 'AUTHOR'), ('GUEST', 'GUEST')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('tag', models.CharField(choices=[('BUG', 'BUG'), ('ENHANCEMENT', 'ENHANCEMENT'), ('TASK', 'TASK')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=30)),
                ('status', models.CharField(choices=[('To-Do', 'To-Do'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed')], max_length=30)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('back end', 'back end'), ('front end', 'front end'), ('iOS', 'iOS'), ('Android', 'Android')], max_length=30)),
            ],
        ),
    ]
